# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://praveenc.github.io',
                'git_url': 'https://github.com/praveenc/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.pycore': { 'nbdev_hello_world.pycore.foo': ('pycore.html#foo', 'nbdev_hello_world/pycore.py'),
                                          'nbdev_hello_world.pycore.say_hello': ('pycore.html#say_hello', 'nbdev_hello_world/pycore.py')}}}
